# Generated by Django 2.2 on 2020-03-22 16:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20200211_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20), size=None),
        ),
    ]
