# Generated by Django 3.0.2 on 2020-02-09 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='category',
            field=models.BooleanField(),
        ),
    ]
