# Generated by Django 3.0.2 on 2020-02-09 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200209_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='telegram',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='viber',
            field=models.BooleanField(default=True),
        ),
    ]
