# Generated by Django 2.2 on 2020-02-10 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200209_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='rub',
            field=models.BooleanField(choices=[('rub', 'gbp'), ('usd', 'eur')], default=True),
        ),
    ]
