# Generated by Django 2.2 on 2020-02-11 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200210_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='glob',
            field=models.BooleanField(default=True, verbose_name='Global'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='eur',
            field=models.BooleanField(default=True, verbose_name='EUR'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gbp',
            field=models.BooleanField(default=True, verbose_name='GBP'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rub',
            field=models.BooleanField(default=True, verbose_name='RUB'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='usd',
            field=models.BooleanField(default=True, verbose_name='USD'),
        ),
    ]
