# Generated by Django 2.2 on 2020-03-24 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200211_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subscription_plan',
            field=models.CharField(blank=True, default='NONE', max_length=100),
        ),
    ]
