# Generated by Django 2.2 on 2020-03-27 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_profile_subscription_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='category',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='recieve_source',
        ),
    ]
